apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-24T02:44:18Z"
  labels:
    app: devops-node-api
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-06-24T02:44:18Z"
  name: devops-node-api
  namespace: default
  resourceVersion: "17859"
  selfLink: /api/v1/namespaces/default/services/devops-node-api
  uid: 7a14d098-76ce-4062-94bf-cd06c6a89e78
spec:
  clusterIP: 10.96.224.15
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30420
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: devops-node-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
